---
# tasks file for prepare_mysqlserver
    - name: install mysql
      apt:
        name:
          - mysql-server
          - mysql-client
        update_cache: yes
        cache_valid_time: 3600
        state: present
     
    - name: start up the mysql service
      shell: "service mysql start"

    - name: ensure mysql is enabled to run on startup
      service:
        name: mysql
        state: started
        enabled: true
